[package]
name = "fts"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4", features = ["derive"] }
quick-xml = { version = "0.32", features = ["serialize"] }
csv = "1.3"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] } 